name: Deploy swa-auth to NPM

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  qa_package:
    name: Lint and Test swa-auth
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  dry_run_build_and_deploy:
    needs: [qa_package]
    if: (github.event_name != 'push' && (github.event_name == 'pull_request' && github.event.action != 'closed'))
    runs-on: ubuntu-latest
    name: Test NPM Deployment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          token: ${{ secrets.NPM_AUTH }}
  build_and_deploy_job:
    needs: [qa_package]
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed'))
    runs-on: ubuntu-latest
    name: Build and Deploy swa-auth to NPM
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH }}
